default_platform(:ios)

platform :ios do

  desc "Run Tests"
  lane :test do
    scan(
    	scheme: "CalendarishCore",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
    scan(
    	scheme: "CalendarishAPI",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
  end

  desc "Distribute to TestFlight"
  lane :distribute do
    sigh
  	build_app(scheme: "Calendarish")
        # Cron will release these later, don't wait for processing
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  	
end
