default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :test do
    scan(
    	scheme: "CalendarishCore",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
    scan(
    	scheme: "CalendarishAPI",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
  end

  desc "Distribute to TestFlight"
  lane :distribute do
  	
  end
  	
end
