default_platform(:ios)

platform :ios do

  desc "Run Tests"
  lane :test do
    scan(
    	scheme: "CalendarishCore",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
    scan(
    	scheme: "CalendarishAPI",
    	devices: ["Apple Watch Series 5 - 44mm"]
    	)
  end

  desc "Distribute to TestFlight"
  lane :distribute do
  	build_app(scheme: "Calendarish")
    upload_to_testflight
  end
  	
end
