name: Distribute

on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Set up signing
      env: 
        SIGNING_DATA: ${{ secrets.SIGNING_DATA }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        PROFILE_DATA: ${{ secrets.PROFILE_DATA }}
      run: ./scripts/configure_signing.sh
    - name: Build
      run: bundle exec fastlane build
    - name: Upload
      env:
        FASTLANE_USER: ${{ secrets.ITC_EMAIL }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.ITC_APP_SPECIFIC_PASSWORD }}
      run: bundle exec fastlane upload
