name: Distribute

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
    - env:
        FASTLANE_USER: ${{ secrets.ITC_EMAIL }}
        FASTLANE_PASSWORD:  ${{ secrets.ITC_PASSWORD }}
      run: fastlane distribute
