name: Distribute

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up signing
      env: 
        SIGNING_DATA: ${{ secrets.SIGNING_DATA }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        PROFILE_DATA: ${{ secrets.PROFILE_DATA }}
      run: |
        # Import certificate and private key
        echo $SIGNING_DATA | base64 -d -o Signing.p12
        security import ./Signing.p12 -k login.keychain -P $SIGNING_PASSWORD
        # Import provisioning profile.
        echo $PROFILE_DATA | base64 -d -o Profile.mobileprovision
    - name: Build
      env:
        FASTLANE_USER: ${{ secrets.ITC_EMAIL }}
        FASTLANE_PASSWORD:  ${{ secrets.ITC_PASSWORD }}
      run: fastlane distribute
